name: Docker Image CI

on:
  push:
    branches:
      - feature/github_CI
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run tests
        run: |
          pytest tests/tests.py

      - name: Build image
        env:
          USERNAME: AlbinBengtssson
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REGISTRY: docker.pkg.github.com
          REPOSITORY: albinbengtssson/run-on-cron
          COMMIT_SHA: ${{ github.sha }}
          IMAGE_NAME: run-on-cron
        run: |
          docker login https://docker.pkg.github.com -u $USERNAME -p $TOKEN
          docker build -t "$REGISTRY/$REPOSITORY:$COMMIT_SHA" -t "$REGISTRY/$REPOSITORY:latest" .
          docker push $REGISTRY/$REPOSITORY/$IMAGE_NAME --all-tags
          docker ps -a
          echo "::set-output name=image::$REGISTRY/$REPOSITORY:$IMAGE_TAG"
